### ISSUE TITLE
Crash when getting apps list with icon

### ISSUE THREAD

**Issue by Grorock** [sharmadhiraj/installed_apps#37]
When I use the package with withIcon to true on my phone, I have this crash :
`
E/AndroidRuntime(28128): FATAL EXCEPTION: Thread-6
E/AndroidRuntime(28128): Process: com.example.test, PID: 28128
E/AndroidRuntime(28128): java.lang.IllegalArgumentException: width and height must be > 0
E/AndroidRuntime(28128): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1107)
E/AndroidRuntime(28128): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1074)
E/AndroidRuntime(28128): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1024)
E/AndroidRuntime(28128): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:985)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.DrawableUtil$Companion.drawableToBitmap(DrawableUtil.kt:24)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.DrawableUtil$Companion.drawableToByteArray(DrawableUtil.kt:13)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.Util$Companion.convertAppToMap(Util.kt:24)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.InstalledAppsPlugin.getInstalledApps(InstalledAppsPlugin.kt:137)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.InstalledAppsPlugin.onMethodCall$lambda$0(InstalledAppsPlugin.kt:76)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.InstalledAppsPlugin.$r8$lambda$CPtibYHRBhI_l0sBJ1895T1x_3Y(Unknown Source:0)
E/AndroidRuntime(28128): 	at com.sharmadhiraj.installed_apps.InstalledAppsPlugin$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/AndroidRuntime(28128): 	at java.lang.Thread.run(Thread.java:1012)
I/Process (28128): Sending signal. PID: 28128 SIG: 9
`
If I set the withIcon to false, it works.

I don't know what app causes this crash.

**Comment by juanmadelboca** [comment]
You have an estimated time to release that fix?

**Comment by leywino** [comment]
I don’t have permission to merge the pull request into the main branch or release it on Pub.

As a temporary solution, you can add my fork directly to your project’s `pubspec.yaml` file as a Git dependency:

```yaml
installed_apps:
  git:
    url: https://github.com/leywino/installed_apps.git
    ref: master


> You have an estimated time to release that fix?
